---

- hosts: all
  sudo: yes
  gather_facts: no

  pre_tasks:

  - name: Update host
    apt: upgrade=dist update_cache=yes

  tasks:

    - include_vars: defaults/main.yml

    - include: tasks/main.yml
