---

- hosts: all
  become: yes
  gather_facts: yes


  vars:

    plone_initial_password: admin

    servers:
      - plone_version: '5.0.7'

        plone_zeo_port: 5100
        plone_client_base_port: 5080
        plone_additional_eggs:
          - collective.recaptcha
          - pas.plugins.authomatic
        plone_sources:
          - "collective.recaptcha = git https://github.com/collective/collective.recaptcha.git rev=tags/1.1.5"
          - "pas.plugins.authomatic = git https://github.com/collective/pas.plugins.authomatic.git update=true depth=1"
        # plone_buildout_cache_file: /home/steve/ssd/nui5.0/packages/buildout-cache.tar.bz2
        plone_buildout_extra_dir: ./meta/
        plone_client_max_memory: 600MB

      - plone_instance_name: p4
        plone_version: '4.3.12'

        plone_initial_password: admin
        plone_zeo_port: 4100
        plone_client_base_port: 4080
        plone_sources:
        plone_extra_parts:
          zopepy: |
            recipe = zc.recipe.egg
            eggs = ${buildout:eggs}
            interpreter = zopepy
            scripts = zopepy

        plone_buildout_extra: |
          allow-picked-versions = false

        plone_additional_versions:
          - "plone4.csrffixes = 1.0.9"
          - "cssselect = 0.9.1"
          - "Products.PloneHotfix20160419 = 1.0"

        plone_client_max_memory: 500MB

        plone_hot_monitor: no

        # plone_buildout_cache_file: /home/steve/ssd/nui4.3/packages/buildout-cache.tar.bz2


  roles:

    - role: ansible.plone_server
      plone_config: "{{ servers[0] }}"

    - role: ansible.plone_server
      plone_config: "{{ servers[1] }}"

  tasks:

    # make sure plone daemons have had time to come up
    - pause: minutes=1

    - pip: name=httplib2

    - name: Check to see if Plone 5 is running
      uri:
        url: http://127.0.0.1:5081/Plone
        method: GET
        status_code: 200

    - name: Check to see if Plone 4.3.x is running
      uri:
        url: http://127.0.0.1:4081/Plone
        method: GET
        status_code: 200

    - stat: path=/usr/local/plone-5.0/zeoserver/main.yml
      register: st
    - fail: msg="copy of extra dir failed"
      when: not st.stat.exists

    - name: Check to see if we copied the extra buildout file
      command: "ls /usr/local/plone-5.0/zeoserver/main.yml"

    - name: Attempt a backup for the P5 install
      command: "/usr/local/plone-5.0/zeoserver/bin/backup"
      become_user: plone_daemon

    - name: Attempt a backup for the P4 install
      command: "/usr/local/plone-4.3/p4/bin/backup"
      become_user: plone_daemon

    - name: Attempt a restore for the P5 install
      command: "/usr/local/plone-5.0/zeoserver/bin/restore -n"
      become_user: plone_daemon

    - name: Attempt a restore for the P4 install
      command: "/usr/local/plone-4.3/p4/bin/restore -n"
      become_user: plone_daemon

    - name: Attempt a pack for the P5 install
      command: "/usr/local/plone-5.0/zeoserver/bin/zeopack"
      become_user: plone_daemon

    - name: Attempt a pack for the P4 install
      command: "/usr/local/plone-4.3/p4/bin/zeopack"
      become_user: plone_daemon

    - name: Check that we're using superlance in the p5 install
      shell: "grep eventlistener /etc/supervisor/conf.d/zeoserver_zeo.conf"

    - name: Check that we're not using superlance in the p4 install
      shell: "[ ! `grep eventlistener /etc/supervisor/conf.d/p4_zeo.conf` ]"
